examples/simpleFit/Makefile

example didn't build for me (using OpenMP, didn't try CUDA).
The reasons were:
* needed to specify c++11
* absence of libCint.so in my ROOT installation
* absence of libMinuit2.so in my ROOT installation
I fixed this by:
* specifying --std=c++11
* removing the hard coded linker flags for ROOT and replace them by root-config

use root-config -- fixes absence of libCint.so in ROOT6

---

CHANGELOG.md
CMakeLists.txt

This is an attempt to fix one of the review points for the GooFit Application merge. This *should* correctly set the definition when compiling.

Fixing definition for MPI

---

.gitignore
CHANGELOG.md
CMakeLists.txt
README.md
docs/CONVERTING20.md
docs/SYSTEM_INSTALL.md

This corrects the OpenMP build flags for the stand alone Minuit 2; the OpenMP flags were leaking from GooFit into Minuit2. GooFit now runs out-of-the box in CentOS and Alpine Docker. Better docs for building.

OMP fixes for standalone GooFit

---

CMakeLists.txt
include/goofit/PdfBase.h
include/goofit/Version.h.in
python/goofit/PdfBase.cpp
python/goofit/Version.cpp
src/goofit/CMakeLists.txt
src/goofit/PdfBase.cc

Fixes based on OpenSUSE docker and missing Minuit2 option for ROOT. Addresses #101.
This means you can now build and use GooFit with a copy of ROOT without Minuit2, since GooFit can use the stand-alone Minuit2 library.

WIP: Fixes nominuit

---

.gitignore
CHANGELOG.md
CMakeLists.txt
Pipfile
README.md
docs/SYSTEM_INSTALL.md
examples/2d_plot/2d_plot.cu
examples/dalitz/dalitz.cu
include/goofit/Application.h
include/goofit/PDFs/physics/DalitzPlotHelpers.h
include/goofit/PDFs/physics/DalitzPlotPdf.h
include/goofit/PDFs/physics/DalitzPlotter.h
include/goofit/detail/Style.h
python/CMakeLists.txt
python/PDFs/physics/DalitzPlotter.cu
python/examples/addition.py
python/examples/dalitz.py
python/goofit.cpp
setup.py
src/PDFs/CMakeLists.txt
src/PDFs/physics/DalitzPlotHelpers.cu
src/PDFs/physics/DalitzPlotPdf.cu
src/PDFs/physics/TddpPdf.cu
src/goofit/CMakeLists.txt

This adds a few fixes and a nice Dalitz plotter interface.
* FeatureDetector works correctly again (regression: it was no longer detecting compiling options)
* Better notes in README about ROOT and CUDA versions
* The GooFit style is set in `GooFit::setROOTStyle()`
* Added `DalitzPlotter`, which helps in making plots of 3-body Dalitz PDFs and toy generation.
* Cleaned up Dalitz example, adding more plotting
* Some Python improvements to `addition.py` and `dalitz.py`
* in Dalitz functions cleaned up and generally available for use in `DalitzPlotHelpers`
* ROOT missing variable improved.

Dalitz plotter tools

---

include/goofit/PDFs/physics/ThreeGaussResolution_Aux.h
include/goofit/PDFs/physics/TruthResolution_Aux.h

This allows `*Resolution_Aux.h` includes to work for now (deprecated).

Adding _Aux redirects

---

CMakeLists.txt
README.md
include/goofit/Application.h
src/goofit/Application.cpp
src/goofit/FitManagerMinuit2.cpp

Before we could only do this:
```
goofit
- goofit_my_package
...
```
This PR allows packages of the form:
```
my_package
- goofit
...
```
This allows a package to use GooFit as a submodule, locking in a specific version, as well as provide faster builds (tests, python, and examples skipped). This is how most other libraries work, and is made possible by proper linking on GooFit's part.

External Packages (BETA feature)

---

.travis.yml

This forcibly installs a local, upgraded colorama. PR made to Numba as well, numba/numba#3384, but this will fix it for now for us.

Colorama is getting imported, and is a very old version with no __version__

---

CMakeLists.txt

And PyBind11 can break with no https support (fix in latest master, pybind/pybind11#1563), but I need to check to see if CUDA support is still broken in PyBind11 > 2.2.2.

Submodules of submodules are not needed 

---

src/PDFs/CMakeLists.txt

Fix a logic bug when using older CMake versions (<3.8) without using CUDA.

Fixing build on old CMake if you don't have CUDA

---

setup.py

This should make selecting options a bit easier from Python, and will be less pip version specific (?).

Support environment variables when building in Python

---

src/PDFs/basic/CrystalBallPdf.cu

The p.d.f. is not working since parameters are registered from 1 to 4 and not to 0 to 3 as it should be. Now seems to be smooth.

CrystallBallPdf Parameter Registration Fix

---

.github/workflows/build.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
CMakeLists.txt
docs/CHANGELOG.md
examples/exponential/exponential2.cpp
noxfile.py
pyproject.toml
python/CMakeLists.txt
python/Minuit2/CMakeLists.txt
python/Minuit2/MnPrint.cpp
python/Minuit2/setup.py
python/examples/quad1f.py
setup.cfg
src/goofit/FitManagerMinuit2.cpp

pyproject.toml no longer pins exactly. Might have an issue with cmake 3.20 or the latest scikit-build, but hopefully we can work those out.
Supports ROOT 6.24's Minuit2 changes (and should work on old ROOTs too).
Updating pybind11, catch2, and Minuit2 (built-in). fmt is stuck at version 5 because newer versions don't support CUDA 8.
Added a noxfile so testing in a fresh, temporary virtual environment is simple and easy. Just run `nox`. (`pipx run nox` if you have pipx but not nox).

fix: support latest versions of some deps

---

.github/workflows/ci.yml
pyproject.toml

Supports macOS Apple Silicon and MSVC 2019 (if we supported Windows, anyway).

chore: bump to scikit-build 0.12

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.pre-commit-config.yaml
include/goofit/Error.h
include/goofit/PDFs/physics/MixingTimeResolution.h

Using https://github.com/ssciwr/clang-format-wheel, 1-2 MB on all common platforms. Docker no longer required. Auto fixes now work. Ultra fast. Pinned to exact consistent versions. Auto updated.

chore: use pip clang format

---

include/goofit/PDFs/ParameterContainer.h
src/PDFs/combine/AddPdf.cu

This should be easier to read, and cleaner. Three changes:
* Using classic return-type-first syntax for methods. The trailing return type was only added for special cases (where you need to compute the return type after the arguments), not for normal int's and floats.
* Make methods `const` that do not change the ParameterContainer.
* Make the parameter container copy the local one, rather than the one that's going to change. Make it `const` to ensure it remains the original PDF parameters.

refactor: nicer PC impl

---

.github/workflows/build.yml
.github/workflows/ci.yml
CMakeLists.txt
README.md
src/PDFs/physics/Amp3Body_TD.cu

Pulled from https://github.com/GooFit/GooFit/pull/307, mostly. Closes #311. Had to drop CUDA 10.0, since it can't be signed anymore. 8.0 and 9.2 still can be. We can try newer versions, but that will require newer thrust.

fix: latest git, avoid defaulting to submodule checkout

---

.github/workflows/ci.yml
python/PDFs/physics/Amp3Body.cpp
python/PDFs/physics/Amp4Body.cu
python/PDFs/physics/Amp4Body_TD.cu

This makes the particle array be a proper 3D array, same shape as MCBooster.
- fix: better particle shape
- chore: bump pybind11 to 2.9.2
- chore: bump catch2 to 2.13.9
- chore: bump CLI11 to 2.2.0

feat(python): nicer particle shape

---

LICENSE
LICENSE.lgpl
README.md
pyproject.toml
setup.cfg
setup.py

Landau needs to come out, too. Also Minuit2. This will be done in a new branch.

refactor: converting license

---

.github/actions/cmake_config/entrypoint.sh
.github/workflows/ci.yml
CMakeLists.txt

Trying to update while avoiding the GCC ICE, partial update from #321.

fix: support newer CMake, drop GOOFIT_CXX_STANDARD flag

---

src/PDFs/physics/lineshapes/FOCUS.cu

Found issue with FOCUS lineshape function which will currently return nan. This is due to the phase space density function, `phsp_FOCUS` returning an fptype instead of fpcomplex. Value returned now seem sensible. 
FYI: @FlorianReiss, @thboettc

Correct phase space density function for FOCUS lineshape

---

CMakeLists.txt
src/PDFs/MetricTaker.cu

Currently the CUDA stack size is set to 50mb in MetricTaker.cu. This causes a very large overhead for older GPU models and leads to very long execution times (~10 minutes to execute exponential.py example on a Tesla K4!!!), even on code which doesn't require this increase in stack size.
To avoid this, set the stack size in CMake by defining a preprocessor macro which can be set by the user as and when a larger stack size is necessary.
Does the way I have defined this macro in CMake mean that this can be set as a CMake flag, e.g. -DCUDA_STACKSIZE=2048?
FYI:@thboettc, @FlorianReiss , @henryiii

Set CUDA stack size in CMake

---

src/PDFs/physics/resonances/RBW.cu

I noticed that the logic for incrementing the cyclic index of the 3-body RBW looked strange, as it always just incremented by `1 % 3 = 1`. I think what I've done here is correct.
@JuanBSLeite could this be related to the issues you were seeing with symmetrization? Could you see if this fixes that issue?
@FlorianReiss @JuanBSLeite @jcob95 it'd be helpful if one of you could double check my logic here.

Draft: Fix logic incrementing cyclic index in RBW

---

python/PDFs/physics/Amp4Body_TD.cu
python/examples/generate_sig_example.py

Fixes a bug causing out of bounds memory accesses in the python binding for `GenerateSig` in `Amp4Body_TD`.

Fix Amp4Body_TD GenerateSig
