GooFit/GooFit

README.md
=> One typo in alternate text that was missed

README.md, include/goofit/PdfBase.h, include/goofit/Variable.h, scripts/find_optimal.py
Provided documentation for MPI and for setting the group/grain size for GPU-only versions.
=> MPI Documentation

.travis.yml
@hassec, you suggested this, look okay?
=> No longer build docs unless this is a release

src/PDFs/MetricTaker.cu
Moving binCenters to global for better performance.
=> Perf fix from Brad

CMakeLists.txt, examples/2d_plot/2d_plot.cu
This should add support for non-minuit2 builds of ROOT, as well as older ROOT 6 (6.04) versions. Please test. Should help #101 .
=> Smartminuit

CMakeLists.txt
I'm now using the new infrastructure for everything it provides. Only remaining FindCUDA part is the arch detection.
=> CUDA improvement

examples/dalitz/dalitz.cu, include/goofit/UnbinnedDataSet.h, include/goofit/Variable.h, scripts/ModernizeGooFit.py, src/PDFs/GooPdf.cu, src/goofit/UnbinnedDataSet.cpp, tests/SimpleTest.cu
This adds event number detection and fixing the grid functions to correctly generate grids without event numbers. `fillWithGrid` is added to UnbinnedDataSets.
=> Grids with event numbers

Pipfile, include/goofit/detail/MonteCarlo.h, include/goofit/fitting/Params.h, python/CMakeLists.txt, python/Minuit2/CMakeLists.txt, python/Minuit2/FCNBase.cpp, python/Minuit2/FunctionMinimum.cpp, python/Minuit2/MinuitParameter.cpp, python/Minuit2/MnApplication.cpp, python/Minuit2/MnMigrad.cpp, python/Minuit2/MnPrint.cpp, python/Minuit2/MnUserCovariance.cpp, python/Minuit2/MnUserParameterState.cpp, python/Minuit2/MnUserParameters.cpp, python/Minuit2/main.cpp, python/Minuit2/setup.py, python/examples/quad1f.py, python/goofit.cpp, python/goofit/FitManager.cpp, src/goofit/CMakeLists.txt, src/goofit/Params.cpp, tests/CMakeLists.txt, tests/MonteCarloTest.cu
This adds an MC generator for 1D PDFs, along with a small example of use as a test.
I've also added the Python Minuit2 module from the branch on the stand-alone repository; this should expand the Minuit2 features available in GooFit, as well as providing a place to develop the Minuit2 module. It could eventually be externalized.
=> MC generator

.ci/check_tidy.sh, .ci/travis.sh, include/goofit/PDFs/physics/DalitzPlotPdf.h, include/goofit/PDFs/physics/DalitzPlotter.h, include/goofit/PDFs/physics/ResonancePdf.h
Access to a few more items, drop forced Poisson fluctuation of event number.
=> A few fixes from symmetry branch unrelated to symmetry

docs/CHANGELOG.md, examples/dalitz/dalitz.cpp, examples/zachFit/zachFit.cpp, python/PDFs/combine/ConvolutionPdf.cpp, python/examples/RunAll.sh, python/examples/addition.py, python/examples/zachFit.py
Includes cleanup for the C++ example too, and one new binding.
=> Add Zachfit to Python examples

docs/documentation.md
To address issue #157, updating documentation to reflect latest changes.
=> Updated documentation

CMakeLists.txt, README.md, include/goofit/PDFs/GooPdf.h, include/goofit/PDFs/physics/DP4Pdf.h, include/goofit/PdfBase.h, src/PDFs/CMakeLists.txt, src/PDFs/GooPdf.cpp, src/PDFs/GooPdf.cu
Dropping `GOOFIT_SEPARATE_COMP`, since `OFF` is not supported. Moving a few CPU parts of GooPdf to a `.cpp` file, mostly to avoid needing a ROOT include in nvcc.
=> Trying to improve compile time a bit

src/PDFs/physics/DP4Pdf.cu, src/PDFs/physics/Tddp4Pdf.cu
Since Amplitudes can have any number of LineShapes or SpinFactors, this PR will track the total to skip when proceeding on to the resolution/efficiency functions.
=> Tracks number of SpinFactors & Lineshapes, skips to end.

src/PDFs/physics/Amp4Body_TD.cu, src/PDFs/physics/detail/AmpCalc_TD.cu, src/PDFs/physics/detail/LSCalculator_TD.cu, src/PDFs/physics/detail/NormIntegrator_TD.cu, src/PDFs/physics/detail/NormLSCalculator_TD.cu, src/PDFs/physics/detail/NormSpinCalculator_TD.cu, src/PDFs/physics/detail/SFCalculator_TD.cu
This should fix the k3pi issues with incorrectly accessing m1->m4 values.
=> Fixed accessing constant values

include/goofit/PDFs/physics/Amp4Body.h, include/goofit/PDFs/physics/Amp4Body_TD.h, src/PDFs/physics/Amp4Body.cu, src/PDFs/physics/Amp4Body_TD.cu
This gives access to the seed, so that more runs can be made.
=> Adding access to mcbooster seed

python/examples/chisquare.py, src/PDFs/basic/SmoothHistogramPdf.cu
Fixed indexing.  Was pointing to 0, not to the bin size.
=> Smooth histogram bug

CMakeLists.txt
Allow setting C++ to C++14 (for OSG ROOT).
=> Stdcontrol

README.md, src/PDFs/physics/CMakeLists.txt
This fixes building with LCG on SLC 6.
=> Fixing build on LxPlus

README.md, include/goofit/utilities/Style.h, src/PDFs/PdfBase.cu, src/goofit/Application.cpp
* Print ROOT version and CUDA version in info
* Support ROOT 6.04, note that 6.16  is supported too
* Fix incorrect parameter push
* Update to CLI11 1.7.1
=> Some fixes

python/PDFs/physics/DalitzPlotter.cpp, scripts/check_style.sh, scripts/check_style_docker.sh, src/PDFs/physics/Amp4Body.cu, src/PDFs/physics/Amp4Body_TD.cu
This was missing in the bindings.
=> Add binding for 2D MC

python/PDFs/physics/Amp3Body_TD.cpp
Add getDataSize to AMp3Body_TD python binding.
=> Added setDataSize to python binding.

.github/workflows/simple.yml
=> Adding Actions CI

LICENSE
=> Include text for LGPL v3

CMakeLists.txt, include/goofit/PDFs/physics/Amp4BodyBase.h, include/goofit/PDFs/physics/DalitzPlotHelpers.h, python/CMakeLists.txt, python/PDFs/physics/MixingTimeResolution.cpp, src/PDFs/physics/Amp4Body.cu, src/PDFs/physics/Amp4BodyBase.cu, src/PDFs/physics/Amp4Body_TD.cu, src/PDFs/physics/CMakeLists.txt
Working on improving 4-body siggen (at the moment).
Also updates some libraries.
=> SigGen improvements

pyproject.toml, python/goofit.cpp, setup.py
Disjoint set of updates compared to #223.
=> Update libs 2

pyproject.toml, python/goofit.cpp, setup.py
Bump library versions carefully. (An update somewhere is causing Dalitz example to hangup)
=> Lib update

.github/workflows/ci.yml, python/CMakeLists.txt, src/goofit/Application.cpp
* Fix bug introduced in #202 (Python could not be run if kMatrix was off)
* Make sure goofit is importable
* Fix bug with `python -m goofit` randomly failing if no GPU present
- Now prints number of GPUs present
* Respect GPU change request when GPU = 0 
Python + CUDA import now tested in CI!
=> Add python build too

.github/workflows/build.yml, .travis.yml, MANIFEST.in
Going to build the sdist on GHA, then upload (because it's a pain to build locally, it loves picking up extra generated files that shouldn't go into an sdist, so it should be a completely clean directory)
=> Add sdist to .github

.github/actions/cmake_config/Dockerfile, .github/actions/cmake_config/action.yml, .github/actions/cmake_config/entrypoint.sh, .github/workflows/ci.yml, CMakeLists.txt
Dropping support for cmake older than 3.9 and CUDA older than 8.0
=> Cleaning up CMakeList.txt

include/goofit/PDFs/physics/detail/Dim2.h, src/PDFs/physics/detail/SpecialResonanceCalculator.cu, src/PDFs/physics/resonances/Resonance.cu
Rolled back changes from Resonance.cu and SpecialResonanceCalculator.cu, modifying dim2.h accordingly.
=> fixing bug in Resonance.cu and SpecialResonanceCalculator.cu

include/goofit/PDFs/detail/Globals.h, include/goofit/PDFs/physics/DalitzPlotHelpers.h, include/goofit/PDFs/physics/resonances/GS.h, include/goofit/PDFs/physics/resonances/LASS.h, include/goofit/PDFs/physics/resonances/RBW.h, include/goofit/PDFs/physics/resonances/Resonance.h, python/PDFs/physics/DalitzPlotHelpers.cpp, python/PDFs/physics/ResonancePdf.cpp, src/PDFs/detail/Globals.cu, src/PDFs/physics/Amp3Body.cu, src/PDFs/physics/Amp3Body_TD.cu, src/PDFs/physics/resonances/GS.cu, src/PDFs/physics/resonances/LASS.cu, src/PDFs/physics/resonances/RBW.cu, src/PDFs/physics/resonances/Resonance.cu
- Add mother meson radius to DecayInfo
- Add D meson form factor to RBW
- Fix incrementIndex in LASS
- Add D meson form factor to LASS
=> Martha fix rbw

.github/workflows/ci.yml, .pre-commit-config.yaml
- ci: print details on failure
- chore: bump style
- ci: minor setup for pre-commit.ci
=> ci: display test output

include/goofit/fitting/FitManagerMinuit2.h, include/goofit/fitting/Params.h, python/Minuit2/CMakeLists.txt, python/Minuit2/MnMinos.cpp, python/Minuit2/MnScan.cpp, python/goofit/FitManager.cpp, src/goofit/FitManagerMinuit2.cpp
cherry-pick improvements to FitManager from branch `martha_cpv` @marthaisabelhilton
=> feat: cherry-pick FitManager improvements

include/goofit/PDFs/physics/ThreeGaussResolutionExt.h, include/goofit/PDFs/physics/ThreeGaussResolutionSplice.h, python/PDFs/physics/CMakeLists.txt, python/PDFs/physics/ThreeGaussResolutionExt.cpp, python/PDFs/physics/ThreeGaussResolutionSplice.cpp, python/goofit.cpp, src/PDFs/physics/Amp3Body.cu, src/PDFs/physics/Amp3Body_TD.cu, src/PDFs/physics/CMakeLists.txt, src/PDFs/physics/ThreeGaussResolution.cu, src/PDFs/physics/ThreeGaussResolutionExt.cu, src/PDFs/physics/ThreeGaussResolutionSplice.cu
same changes as in #304 , but cherry-picked to make merging easier
* decay-time acceptance using two exponential functions for Amp3Body_TD
* decay-time acceptance using cubic splines for Amp3Body_TD
=> add new decay time acceptance models for Amp3Body

src/PDFs/GooPdf.cu, src/PDFs/combine/AddPdf.cu, tests/PDFs/GenArgusTest.cpp, tests/PDFs/GenGaussianTest.cpp, tests/simple/BinningTest.cpp
Resolves https://github.com/GooFit/GooFit/issues/249. We could also fix this on the minuit side. If we agree that the solution in this PR is correct, we can un-draft and merge.
FYI @JuanBSLeite @FlorianReiss
=> Draft: Remove factors of 2 from NLL to get correct errors from minuit
